export const LEASING_ORDER_CATEGORY = Object.freeze({
  REGULAR: "REGULAR",
  AD_HOC: "AD_HOC",
  REPLENISHMENT: "REPLENISHMENT",
  ALLOCATION: "ALLOCATION",
  RETURN: "RETURN",
  ADJUSTMENT: "ADJUSTMENT",
});

export const ORDER_TYPE = Object.freeze({
  WASHING: "WASHING",
  RENTAL: "RENTAL",
  LEASING: "LEASING",
});

export const ORDER_STATUS = Object.freeze({
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  IN_PROGRESS: "IN_PROGRESS",
  READY: "READY",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
});
